### ISSUE TITLE
Missing .util.node_util

### ISSUE THREAD

**Issue by HastagGuigui** [HENDRIX-ZT2/bfb-blender#6]
Was trying to export a model to bfb then this error appeared

```
Traceback (most recent call last):
  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bfb-blender-blender29\__init__.py", line 193, in execute
    errors = export_bfb.save(self, context, **keywords)
  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bfb-blender-blender29\export_bfb.py", line 229, in save
    from . import batch_bfb
  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bfb-blender-blender29\batch_bfb.py", line 7, in <module>
    from .import_bfb import LOD
  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\bfb-blender-blender29\import_bfb.py", line 9, in <module>
    from .util.node_util import *
ModuleNotFoundError: No module named 'bfb-blender-blender29.util.node_util'

location: <unknown location>:-1


```

Where is the node_util file in question?

**Comment by 404ryannotfound** [comment]
Hi @HastagGuigui , you got this running ok? I have Blender 2.93.4 tried to install but get a "Upgrade to 2.8x required" warning, and it won't work =/

**Comment by zene-uk** [comment]
@404ryannotfound the blender29 branch is for blender 2.9x but there is the issue that @HastagGuigui stated.

**Comment by HENDRIX-ZT2** [comment]
fixed
