### ISSUE TITLE
No module named 'bfb-blender-blender3.util.node_util'

### ISSUE THREAD

**Issue by froggyfreaker** [HENDRIX-ZT2/bfb-blender#8]
When trying to import .bfb files with the Blender3 branch, I receive this error.

scene_niftools.ui.material', 'io_scene_niftools.ui.object', 'io_scene_niftools.ui.operators', 'io_scene_niftools.ui.shader', 'io_scene_niftools.ui.scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.update', 'io_scene_niftools.properties', 'io_scene_niftools.operators', 'io_scene_niftools.ui']
Traceback (most recent call last):
  File "C:\Users\techn\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\bfb-blender-blender3\__init__.py", line 128, in execute
    from . import import_bfb
  File "C:\Users\techn\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\bfb-blender-blender3\import_bfb.py", line 9, in <module>
    from .util.node_util import *
ModuleNotFoundError: No module named 'bfb-blender-blender3.util.node_util'

I am using Blender 3.4.

**Comment by xiaohong23** [comment]
same here, any solution?

**Comment by xiaohong23** [comment]
Rename https://github.com/HENDRIX-ZT2/bfb-blender/blob/blender3/util/node_arrange.py to node_util can solve this problem.

**Comment by xiaohong23** [comment]
node_util.py

**Comment by HENDRIX-ZT2** [comment]
fixed
